name: Deploy CIPP-API to Azure Function App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: func-ran-cipp-prod-aue-001
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}